### ISSUE TITLE
BadRequest for GetInventoryAsync with active_only set to true

### ISSUE THREAD

**Issue by norberto5** [stephanstapel/BrickOwlSharp#2]
`System.Net.Http.HttpRequestException: 'Received status code BadRequest for url https://api.brickowl.com:443/v1/inventory/list?active_only=True'`

Based on docs, it should be either 1 or 0, not True or False

> active_only (Optional) - Include only items that are for sale and have a quantity > 0. 0 or 1. Default: 1
[API docs](https://www.brickowl.com/api_docs#:~:text=active_only%20(Optional)%20%2D%20Include%20only%20items%20that%20are%20for%20sale%20and%20have%20a%20quantity%20%3E%200.%200%20or%201.%20Default%3A%201)

Reproduction code:
`await client.GetInventoryAsync(activeOnly: true);`

**Comment by stephanstapel** [comment]
yep, that's right:

https://github.com/stephanstapel/BrickOwlSharp/blob/1ae651df446f3ed7308ced33e30a2da02c56afd4/BrickOwlSharp.Client/BrickOwlClient.cs#L255
